name: Build And Release On Tag

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

permissions:
  contents: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest commit
        uses: actions/checkout@v4
        with:
            show-progress: true
            lfs: false

      - name: Setup Python 3.13 x64
        uses: actions/setup-python@v5
        with:
            python-version: '3.13'
            architecture: 'x64'

      - name: Build the project
        run: |
          pip install poetry
          poetry install
          make build

      - name: Release the project
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist/html
